name: Deployment

on: #this workflow runs on pull requests and pushes to main or master
  push:
    branches: [main, master, test]

#this is a list of all jobs
jobs:
  deploy: #name of first job
    runs-on: ubuntu-latest #sets the env which this job runs on
    permissions:
      contents: write
    steps: #defines the steps necessary
      - name: Checkout #checks out our current branch so this runner has the latest code
        uses: actions/checkout@v4 #uses means that it is a pre-defined action supplied by GitHub.
      - name: Setup Node
        uses: actions/setup-node@v3 #this is also a pre-defined action
        with:
          node-version: 20

      - name: NPM Install #we now need to install all our dependencies in this environment
        run: npm ci #npm clean install - does not write to package.json
      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
